---
- name: PHP | APT install
  apt:
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
    state: present

- name: PHP | PHP {{ php_version }} Ubuntu repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: PHP | Install
  become: true
  apt:
    update_cache: yes
    name:
      - "php{{ php_version }}-redis"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-ctype"
      - "php{{ php_version }}-iconv"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-mysql"
    state: present

- name: PHP | Composer
  script:
    cmd: ../files/composer.sh
    creates: /usr/local/bin/composer

- name: PHP | Prod confinguration
  template:
    src: php.ini
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
  notify: php restart
